#!/usr/bin/env python3
"""Scan for non-code files that are candidates for removal."""

import os
from pathlib import Path
from collections import defaultdict

ROOT = Path(".")

categories = {
    "conflicted": [],  # Dropbox sync conflicts
    "sourcemaps": [],  # .map files (generated)
    "wat": [],  # .wat text WASM (generated)
    "build_dist": [],  # dist/ committed artifacts
    "build_lib": [],  # lib/ committed artifacts
    "coverage": [],  # coverage reports
    "empty": [],  # 0-byte files
    "temp_txt": [],  # .txt temp/log files
    "sub_locks": [],  # package-lock.json in subdirs
    "dropbox_meta": [],  # .dropbox files
    "ds_store": [],  # .DS_Store
}

for p in sorted(ROOT.rglob("*")):
    if not p.is_file():
        continue
    rel = str(p.relative_to(ROOT)).replace(os.sep, "/")
    if ".git/" in rel or "node_modules/" in rel or "/target/" in rel:
        continue

    size = p.stat().st_size
    name = p.name

    if "conflicted" in name:
        categories["conflicted"].append((rel, size))
    elif name.endswith(".map"):
        categories["sourcemaps"].append((rel, size))
    elif name.endswith(".wat"):
        categories["wat"].append((rel, size))
    elif rel.startswith("dist/"):
        categories["build_dist"].append((rel, size))
    elif rel.startswith("lib/") and not rel.startswith("lib/wasm/"):
        categories["build_lib"].append((rel, size))
    elif "coverage" in rel.lower() and not rel.startswith("tools/"):
        categories["coverage"].append((rel, size))
    elif size == 0:
        categories["empty"].append((rel, size))
    elif name.endswith(".txt") and not rel.startswith("docs/"):
        categories["temp_txt"].append((rel, size))
    elif name == "package-lock.json" and rel != "package-lock.json":
        categories["sub_locks"].append((rel, size))
    elif name == ".DS_Store":
        categories["ds_store"].append((rel, size))
    elif name.startswith(".dropbox"):
        categories["dropbox_meta"].append((rel, size))

labels = {
    "conflicted": (
        "Dropbox conflicted copies",
        "SAFE TO DELETE — sync artifacts, never intentional",
    ),
    "sourcemaps": (
        "Source map files (.map)",
        "SAFE — generated by build, add to .gitignore",
    ),
    "wat": (
        "WAT text format (.wat)",
        "SAFE — generated from AS compile, regeneratable",
    ),
    "build_dist": (
        "Build output in dist/",
        "CHECK — per CLAUDE.md, should not be committed",
    ),
    "build_lib": (
        "Build output in lib/ (excl. WASM)",
        "CHECK — per CLAUDE.md, should not be committed",
    ),
    "coverage": ("Coverage reports", "SAFE — generated by test runs"),
    "empty": ("Empty files (0 bytes)", "CHECK — may be intentional placeholders"),
    "temp_txt": (".txt files (non-docs)", "CHECK — may be temp/log files"),
    "sub_locks": (
        "Subdirectory package-lock.json",
        "OPTIONAL — large, regeneratable with npm install",
    ),
    "ds_store": (".DS_Store files", "SAFE — macOS metadata, should be in .gitignore"),
    "dropbox_meta": ("Dropbox metadata files", "SAFE — sync artifacts"),
}

print("=" * 70)
print(" NON-CODE REMOVAL CANDIDATES")
print("=" * 70)

grand_total_files = 0
grand_total_bytes = 0

for key in [
    "conflicted",
    "sourcemaps",
    "wat",
    "build_dist",
    "build_lib",
    "coverage",
    "empty",
    "temp_txt",
    "sub_locks",
    "ds_store",
    "dropbox_meta",
]:
    items = categories[key]
    if not items:
        continue

    label, safety = labels[key]
    total_bytes = sum(s for _, s in items)
    grand_total_files += len(items)
    grand_total_bytes += total_bytes

    if total_bytes > 1024 * 1024:
        size_str = f"{total_bytes / (1024 * 1024):.1f} MB"
    elif total_bytes > 1024:
        size_str = f"{total_bytes / 1024:.0f} KB"
    else:
        size_str = f"{total_bytes} bytes"

    print(f"\n  {label}: {len(items)} files ({size_str})")
    print(f"  [{safety}]")
    for rel, sz in items[:8]:
        print(f"    {rel}  ({sz:,} bytes)")
    if len(items) > 8:
        print(f"    ... +{len(items) - 8} more")

print(f"\n{'=' * 70}")
if grand_total_bytes > 1024 * 1024:
    size_str = f"{grand_total_bytes / (1024 * 1024):.1f} MB"
else:
    size_str = f"{grand_total_bytes / 1024:.0f} KB"
print(f" TOTAL: {grand_total_files} files, {size_str}")
print(f"{'=' * 70}")

# Summary for quick action
safe_count = sum(
    len(categories[k])
    for k in ["conflicted", "sourcemaps", "wat", "coverage", "ds_store", "dropbox_meta"]
)
safe_bytes = sum(
    sum(s for _, s in categories[k])
    for k in ["conflicted", "sourcemaps", "wat", "coverage", "ds_store", "dropbox_meta"]
)
print(
    f"\n SAFE to delete immediately: {safe_count} files ({safe_bytes / (1024 * 1024):.1f} MB)"
)
print(f" Needs review before delete: {grand_total_files - safe_count} files")
