#!/usr/bin/env node
// Sync src/version.js with the version field from package.json.
// Used as a pre-publish guard to keep the runtime-exported `version`
// string in lock-step with package.json (which is the source of truth).
//
// Usage: node tools/sync-version.mjs
//
// The full build (`npm run build` / `npm run compile`) regenerates
// src/version.js as part of the gulp pipeline. This standalone script
// exists for environments where running the full build is too heavy
// (e.g. the WASM/rust toolchain isn't available) but we still want to
// guarantee the published package's runtime version matches the
// package manifest.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const pkgPath = join(here, '..', 'package.json')
const versionPath = join(here, '..', 'src', 'version.js')

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
const target = pkg.version

const banner =
  '// Note: This file is automatically generated when building math.js.\n' +
  '// Changes made in this file will be overwritten.\n'

const out = `export const version = '${target}'\n${banner}`

const current = readFileSync(versionPath, 'utf8')
if (current === out) {
  console.log(`[sync-version] src/version.js already matches package.json (${target})`)
} else {
  writeFileSync(versionPath, out)
  console.log(`[sync-version] src/version.js updated to ${target}`)
}
